name: tests
on: workflow_dispatch

permissions: read-all

jobs:
  tests_self_hosted:
    runs-on: [self-hosted, macos]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter test
      - run: flutter test -d macos integration_test/smoke_test.dart
